server:
  port: 8080
  servlet:
    context-path: /lala
spring:
  datasource:
    url: "jdbc:mysql://localhost:3308/lala_db?createDatabaseIfNotExist=true"
    username: root
    password: 122002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

auth:
  token:
    expirationInMils: 3600000
    jwtSecret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
